CREATE TABLE `gary_giveaways` (
	`id` TINYINT(4) NOT NULL AUTO_INCREMENT,
	`message_id` BIGINT(20) NULL DEFAULT NULL,
	`time` INT(11) NULL DEFAULT NULL,
	`prize` TEXT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;